version: '3'
services:
  jenkins:
    container_name: jenkins
    image: 'jenkins/jenkins'
    ports:
      - "8080:8080"
    volumes:
      - "C:\\Users\\super\\Documents\\databases\\jenkins_aws\\jenkins_home:/var/jenkins_home"
    networks:
      - net
networks:
  net: 